### ISSUE TITLE
Phrase.getText() not work.

### ISSUE THREAD

**Issue by rrifafauzikomara** [phrase/flutter_sdk_example#12]
Hi all, after generated the phrase. I try to call the content dynamic by `key`. I found on `phrase_base.dart.dart` we can do it by this code.

```dart
Phrase.getText(localeName, key);
```

After testing it, it's not working.

Even I clone this project, `Phrase.getText` returning `null`.
```dart
AppLocalizations.of(context).textSimple; // can get value
Phrase.getText('en', 'textSimple'); // can't get value but returning null
```

**Comment by theSoenke** [comment]
Hey @rrifafauzikomara, is it maybe possible that translations for `en` have not been fetched yet? Maybe you could do something like this to make sure the same locale is used in both cases:

```
Locale currentLocale = Localizations.localeOf(context);
String localeCode = Intl.canonicalizedLocale(currentLocale.toString());
```

And in the first case it should also use the bundled translations from the app as fallback in case translations have not been fetched yet

**Comment by rrifafauzikomara** [comment]
@theSoenke thanks it's work!
