### ISSUE TITLE
Update of the dependencies

### ISSUE THREAD

**Issue by FDuhen** [phrase/flutter_sdk_example#13]
The Phrase SDK is depending on `package_info_plus` package. 
The current version of `package_info_plus` is **3.1.0**
The current version used in phrase is **1.3.0** 

Could you please update it ?

**Comment by theSoenke** [comment]
Hi @FDuhen, thanks for raising it and we'll try to get out a new version quickly with an updated `package_info_plus`

**Comment by theSoenke** [comment]
@FDuhen version 1.1.1 was released yesterday and should fix is by relaxing the version constraint
