### ISSUE TITLE
chore(deps): please update `package_info_plus` constraints 

### ISSUE THREAD

**Issue by tsinis** [phrase/flutter_sdk_example#17]
Hey Phrase Team!

Thanks for your great job in the first place. The current version of the `phrase` package is 2.0.0 and requires `package_info_plus` >=1.3.0 <4.0.0. But current `package_info_plus` version is [4.0.2](https://pub.dev/packages/package_info_plus). It brings a lot of issues of other packages that are also dependent on `package_info_plus`.

**Comment by theSoenke** [comment]
Hi @tsinis, thanks for the report! I'll try to make sure to publish a new release soon and removing this constraint

**Comment by theSoenke** [comment]
@tsinis version 2.0.1 is now published and should resolve it
