### ISSUE TITLE
Phrase flutter

### ISSUE THREAD

**Issue by Kiruel** [phrase/flutter_sdk_example#2]
Hi, it's can be nice to have a repository "phrase-flutter" on your organisation for makings issues for this library: https://pub.dev/packages/phrase
(Because I can't find the repository related).
Thanks,

**Comment by docstun** [comment]
@Kiruel thanks for the suggestion. We created a new home for issues based on your suggestion: https://github.com/phrase/phrase-flutter-sdk

Please feel free to share any issues you're observing. We'll add more useful information soon.
