### ISSUE TITLE
Feature request (Flutter): Deleting the cache on the local device

### ISSUE THREAD

**Issue by Neelansh-ns** [phrase/flutter_sdk_example#4]
Hi

I saw a case where if I create a new OTA release, and get the values downloaded and saved on my local device. Now if I want to use the embedded values in the .arb files packed in the APK, I simply can't do that.

I tried deleting the release created. It gives a 404 error but still takes the value for a key from the cached value. I tried deleting the distribution as well and achieved the same 404 error. Now I don't have a way to clear the cached values on a user's device.

I was looking to fork the repo, and do the modification, but couldn't find the public repo for flutter SDK. Hence creating an issue on the example package.

**Comment by forelabs** [comment]
Hi @Neelansh-ns,

sorry for the late reply.

We are still in the process of finding the right solution to be able to clear the users cache.
In the meantime you can just create a new release with the apps defaults, this will then be fetched by the users devices and overwrite the previous release. You can combine this with our branching feature to hold the aps defaults in that branch and create a release from that branch.

**Comment by theSoenke** [comment]
Hi @Neelansh-ns, this should now be resolved with the latest release 2.2.1. When the distribution is deleted or no matching release can be found the cache on the device will be cleared

**Comment by Neelansh-ns** [comment]
> Hi @Neelansh-ns, this should now be resolved with the latest release 2.2.1. When the distribution is deleted or no matching release can be found the cache on the device will be cleared

Thanks @theSoenke 🙌🏻
