### ISSUE TITLE
Feature Request : Translating a String variable

### ISSUE THREAD

**Issue by FDuhen** [phrase/flutter_sdk_example#5]
I'd like to be able to translate a String received from a REST API.  
I'd gladly fork the SDK to implement it myself but I couldn't find the source code on Phrase's Github.  

Expected method :  
```
final stringKey = 'my_key';
final translation = AppLocalizations.of(this).translateKey(stringKey);
```

**Comment by theSoenke** [comment]
Hi @FDuhen, thanks for raising this. The SDK code is currently not public and accessing the Over-air-translations is not directly exposed via an API interface. This looks like it could be quite handy and I've created a feature task to look into adding this to the SDK

**Comment by FDuhen** [comment]
Any updates on this ?

**Comment by theSoenke** [comment]
As a short update there is already a way to access translations via a translation keys like this `Phrase.getText(<locale>, <key>)`. The API is just not so convenient yet as you have to pass in the locale yourself and there is no fallback to bundled translation. It is on our roadmap for the SDK to make this a bit easier

**Comment by theSoenke** [comment]
Hi @FDuhen, this is now supported with the latest release 2.1.0. With `  Text(AppLocalizations.of(context).getText('keyName'))` you can access translation by their key name.

https://pub.dev/packages/phrase
