### ISSUE TITLE
Problem with generating builds

### ISSUE THREAD

**Issue by Mik77o** [phrase/flutter_sdk_example#7]
_Error: Couldn't resolve the package 'flutter_gen' in 'package:flutter_gen/gen_l10n/phrase_localizations.dart'_ - 
When I generate a new build locally, everything works. When I use codemagic I get errors like this. 
Could something be missing in the configuration?

From codemagic: 
```
flutter pub get
flutter packages pub run build_runner build --delete-conflicting-outputs
```

When I tried to use the command from the documentation it didn't help.

```
flutter pub get
flutter pub run phrase
flutter packages pub run build_runner build --delete-conflicting-outputs
```

Locally
![Screenshot 2022-12-06 at 13 20 13](https://user-images.githubusercontent.com/26656256/205911269-4ad52ed1-f22b-462e-a2fa-21b5ccfccd65.png)

`main.dart`
```
    ...
    localizationsDelegates: PhraseLocalizations.localizationsDelegates,
    supportedLocales: PhraseLocalizations.supportedLocales,
    ...
```

**Comment by theSoenke** [comment]
Hi @Mik77o, could you try setting `synthetic-package` to false in in l10n.yaml and check whether this makes any difference?

**Comment by Mik77o** [comment]
> Hi @Mik77o, could you try setting `synthetic-package` to false in in l10n.yaml and check whether this makes any difference?

Okay, I will try :)

**Comment by Mik77o** [comment]
@theSoenke I got:
_'phrase_localizations.dart' has been successfully created
flutter packages pub run build_runner build --delete-conflicting-outputs
Unhandled exception:_
_bad state: Unable to generate package graph, no `/Users/builder/clone/.dart_tool/flutter_gen/pubspec.yaml` found.
#0      _pubspecForPath (package:build_runner_core/src/package_graph/package_graph.dart:232:5)
#1      _parsePackageDependencies (package:build_runner_core/src/package_graph/package_graph.dart:206:21)
#2      PackageGraph.forPath (package:build_runner_core/src/package_graph/package_graph.dart:101:33)
<asynchronous suspension>
#3      main (file:///Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-2.3.2/bin/build_runner.dart:27:30)
<asynchronous suspension>
pub finished with exit code 255
make: *** [generate-code] Error 255_

**Comment by Mik77o** [comment]
@theSoenke I found something like that: https://github.com/dart-lang/build/issues/2835#issuecomment-703528119

**Comment by Mik77o** [comment]
@theSoenke For some reason, running `flutter packages pub get` instead of `flutter pub get `for codemagic build script solved my issue (solution from the community). Now build is generated and OTA is working...

**Comment by theSoenke** [comment]
@Mik77o Glad this is working now! And thanks for posting the solution in case anyone else runs into the same issue

**Comment by Mik77o** [comment]
> @Mik77o Glad this is working now! And thanks for posting the solution in case anyone else runs into the same issue

Yes, it's very interesting how these two commands differ because according to the documentation they mean the same thing.
