### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by rrifafauzikomara** [phrase/flutter_sdk_example#8]
Where's the example of unit testing?

**Comment by theSoenke** [comment]
Hi @rrifafauzikomara, could you provide some examples what you would like to test? Maybe we could then add some more documentation and examples. It could even make sense to skip the `updateTranslations` call during testing

**Comment by rrifafauzikomara** [comment]
Hi @theSoenke , I need to test/verify the `widget` by `text` from the localization.

Example:
```dart
expect(find.text(AppLocalizations.of(context)!.profileScreenSignOut), findsOneWidget);
```

Currently, it's really hard to test for me because every call the localization, it always needs a `context`, and when I add mock context, get a new error. Because of that, prev I thought you have some examples of unit testing, but when I check, nothing..

**Comment by theSoenke** [comment]
@rrifafauzikomara thanks a lot for the explanation. And just to clarify when you mock the context without using the Phrase SDK it works fine?

**Comment by rrifafauzikomara** [comment]
@theSoenke yes it's work, like mock `context` to verify `Navigator.push(context)`

**Comment by theSoenke** [comment]
@rrifafauzikomara thanks. We added some example here: https://github.com/phrase/flutter_sdk_example/pull/11 Could you take a look whether this solves your question?

**Comment by rrifafauzikomara** [comment]
@theSoenke Thanks for the example!
