### ISSUE TITLE
Modified generated code

### ISSUE THREAD

**Issue by rrifafauzikomara** [phrase/flutter_sdk_example#9]
Hi, how to modified generated code from phrase?

For example, here is the example of generated code:
```dart
abstract class AppLocalizations {
  ...

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  ...
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  ...

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(lookupAppLocalizations(locale));
  }

  ...
}

AppLocalizations lookupAppLocalizations(Locale locale) {
  ...
}
```

But I need to modified that code to this:
```dart
/// new line code
Locale _currentLocale = const Locale('en');

abstract class AppLocalizations {
  ...

  /// modified code
  static AppLocalizations of() {
    return lookupAppLocalizations(_currentLocale);
  }

  /// new line code
  static Locale get currentLocale => _currentLocale;

  ...
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  ...

  @override
  Future<AppLocalizations> load(Locale locale) {
    /// new line code
    _currentLocale = locale;
    return SynchronousFuture<AppLocalizations>(lookupAppLocalizations(locale));
  }

  ...
}

AppLocalizations lookupAppLocalizations(Locale locale) {
  ...
}
```

It's possible to do? if yes, can u share the docs for that or tell me how to do it? 

The reason why i need to modified the generated code are:
- hard to get localization because always needed a `context` (u can see first example code above) and also not testable coz of a `context`.
- every I generated new phrase, my modified code always replaced

**Comment by theSoenke** [comment]
Hi @rrifafauzikomara, the auto-generated code currently cannot really be modified. Does providing some examples how to do the testing already helps with this issue as well? https://github.com/phrase/flutter_sdk_example/issues/8

**Comment by rrifafauzikomara** [comment]
@theSoenke Do you have plan to make it modified?

**Comment by theSoenke** [comment]
@rrifafauzikomara I think currently this is not planned. The interface of `AppLocalizations` should also match the method in the `intl` package, which also requires a `context` object.

**Comment by theSoenke** [comment]
Closing for now as it's not part of the current roadmap
